In [1]:
import tensorflow as tf
import numpy as np

sess = tf.Session()

In [2]:
tf.__version__

'1.13.1'

In [4]:
ones_1d = np.ones(5)
ones_1d

array([1., 1., 1., 1., 1.])

In [5]:
weight_1d = np.ones(3)
weight_1d

array([1., 1., 1.])

In [6]:
strides_1d = 1

In [11]:
input_1d = tf.constant(ones_1d, dtype=tf.float32)
input_1d.shape

TensorShape([Dimension(5)])

In [12]:
filter_1d = tf.constant(weight_1d, dtype=tf.float32)
filter_1d.shape

TensorShape([Dimension(3)])

In [15]:
input_width = int(input_1d.shape[0])
filter_width = int(filter_1d.shape[0])
print(input_width)
print(filter_width)

5
3


In [29]:
help(tf.reshape)

Help on function reshape in module tensorflow.python.ops.gen_array_ops:

reshape(tensor, shape, name=None)
    Reshapes a tensor.
    
    Given `tensor`, this operation returns a tensor that has the same values
    as `tensor` with shape `shape`.
    
    If one component of `shape` is the special value -1, the size of that dimension
    is computed so that the total size remains constant.  In particular, a `shape`
    of `[-1]` flattens into 1-D.  At most one component of `shape` can be -1.
    
    If `shape` is 1-D or higher, then the operation returns a tensor with shape
    `shape` filled with the values of `tensor`. In this case, the number of elements
    implied by `shape` must be the same as the number of elements in `tensor`.
    
    For example:
    
    ```
    # tensor 't' is [1, 2, 3, 4, 5, 6, 7, 8, 9]
    # tensor 't' has shape [9]
    reshape(t, [3, 3]) ==> [[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9]]
    
    # tensor 't' 

In [16]:
input_rsh_1d = tf.reshape(input_1d, [1, input_width, 1])
kernel_rsh_1d = tf.reshape(filter_1d, [filter_width, 1, 1])
print(input_rsh_1d.shape)
print(kernel_rsh_1d.shape)

(1, 5, 1)
(3, 1, 1)


In [17]:
help(tf.nn.conv1d)

Help on function conv1d in module tensorflow.python.ops.nn_ops:

conv1d(value, filters, stride, padding, use_cudnn_on_gpu=None, data_format=None, name=None)
    Computes a 1-D convolution given 3-D input and filter tensors. (deprecated argument values) (deprecated argument values)
    
    Instructions for updating:
    `NCHW` for data_format is deprecated, use `NCW` instead
    
    Instructions for updating:
    `NHWC` for data_format is deprecated, use `NWC` instead
    
    Given an input tensor of shape
      [batch, in_width, in_channels]
    if data_format is "NWC", or
      [batch, in_channels, in_width]
    if data_format is "NCW",
    and a filter / kernel tensor of shape
    [filter_width, in_channels, out_channels], this op reshapes
    the arguments to pass them to conv2d to perform the equivalent
    convolution operation.
    
    Internally, this op reshapes the input tensors and invokes `tf.nn.conv2d`.
    For example, if `data_format` does not start with "NC", a tenso

In [18]:
help(tf.squeeze)

Help on function squeeze in module tensorflow.python.ops.array_ops:

squeeze(input, axis=None, name=None, squeeze_dims=None)
    Removes dimensions of size 1 from the shape of a tensor. (deprecated arguments)
    
    Instructions for updating:
    Use the `axis` argument instead
    
    Given a tensor `input`, this operation returns a tensor of the same type with
    all dimensions of size 1 removed. If you don't want to remove all size 1
    dimensions, you can remove specific size 1 dimensions by specifying
    `axis`.
    
    For example:
    
    ```python
    # 't' is a tensor of shape [1, 2, 1, 3, 1, 1]
    tf.shape(tf.squeeze(t))  # [2, 3]
    ```
    
    Or, to remove specific size 1 dimensions:
    
    ```python
    # 't' is a tensor of shape [1, 2, 1, 3, 1, 1]
    tf.shape(tf.squeeze(t, [2, 4]))  # [1, 2, 3, 1]
    ```
    
    Args:
      input: A `Tensor`. The `input` to squeeze.
      axis: An optional list of `ints`. Defaults to `[]`.
        If specified, only squee

In [23]:
help(tf.Tensor)

Help on class Tensor in module tensorflow.python.framework.ops:

class Tensor(_TensorLike)
 |  Tensor(op, value_index, dtype)
 |  
 |  Represents one of the outputs of an `Operation`.
 |  
 |  A `Tensor` is a symbolic handle to one of the outputs of an
 |  `Operation`. It does not hold the values of that operation's output,
 |  but instead provides a means of computing those values in a
 |  TensorFlow `tf.Session`.
 |  
 |  This class has two primary purposes:
 |  
 |  1. A `Tensor` can be passed as an input to another `Operation`.
 |     This builds a dataflow connection between operations, which
 |     enables TensorFlow to execute an entire `Graph` that represents a
 |     large, multi-step computation.
 |  
 |  2. After the graph has been launched in a session, the value of the
 |     `Tensor` can be computed by passing it to
 |     `tf.Session.run`.
 |     `t.eval()` is a shortcut for calling
 |     `tf.get_default_session().run(t)`.
 |  
 |  In the following example, `c`, `d`, an

In [26]:
tf.squeeze(tf.constant([1,2,1,3,1,1]), [2,4]).shape

ValueError: squeeze_dims[0] not in [-1,1). for 'Squeeze_2' (op: 'Squeeze') with input shapes: [6].

In [25]:
tf.squeeze(tf.constant([1,2,1,3,1,1])).shape

TensorShape([Dimension(6)])

In [28]:
print(input_rsh_1d, kernel_rsh_1d, strides_1d)

Tensor("Reshape:0", shape=(1, 5, 1), dtype=float32) Tensor("Reshape_1:0", shape=(3, 1, 1), dtype=float32) 1


In [32]:
output_1d = tf.nn.conv1d(input_rsh_1d, kernel_rsh_1d, strides_1d, padding='SAME')

In [36]:
output_1d # (1,5,1)
output_sqz_1d = tf.squeeze(output_1d) # (5)

In [40]:
print(output_1d.shape)
print(output_sqz_1d.shape)

(1, 5, 1)
(5,)


In [37]:
print( sess.run(output_1d) )
print( sess.run(output_sqz_1d) )

[[[2.]
  [3.]
  [3.]
  [3.]
  [2.]]]
[2. 3. 3. 3. 2.]


In [41]:
output_sqz.1d

[]

In [44]:
help(tf.get_default_graph())

Help on Graph in module tensorflow.python.framework.ops object:

class Graph(builtins.object)
 |  A TensorFlow computation, represented as a dataflow graph.
 |  
 |  A `Graph` contains a set of
 |  `tf.Operation` objects,
 |  which represent units of computation; and
 |  `tf.Tensor` objects, which represent
 |  the units of data that flow between operations.
 |  
 |  A default `Graph` is always registered, and accessible by calling
 |  `tf.get_default_graph`.
 |  To add an operation to the default graph, simply call one of the functions
 |  that defines a new `Operation`:
 |  
 |  ```python
 |  c = tf.constant(4.0)
 |  assert c.graph is tf.get_default_graph()
 |  ```
 |  
 |  Another typical usage involves the
 |  `tf.Graph.as_default`
 |  context manager, which overrides the current default graph for the
 |  lifetime of the context:
 |  
 |  ```python
 |  g = tf.Graph()
 |  with g.as_default():
 |    # Define operations and tensors in `g`.
 |    c = tf.constant(30.0)
 |    assert c.gr